In [2]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row 5 column
print(arr2)
print(arr2.shape)

[1 2 3 4 5]
(5,)


In [7]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [8]:
arr2 = np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [ ]:
np.arange(0,10,2).reshape(5,1) # 5 rows and 1 column in 0 to 10 and step is 2

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
arr = np.array([[1,2,3,4,5], [2,3,4,5,6]])
print("Array : \n", arr)
print("Shape : ", arr.shape)
print("Number of dimensions : ", arr.ndim)
print("Data type : ", arr.dtype)
print("Item size (in bytes) : ", arr.itemsize)

Array : 
 [[1 2 3 4 5]
 [2 3 4 5 6]]
Shape :  (2, 5)
Number of dimensions :  2
Data type :  int64
Item size (in bytes) :  8


In [17]:
arr1 = np.array([2,4,6,8,10]);
arr2 = np.array([1,2,3,4,5]);
print("Addition : " , arr1 + arr2)
print("Substraction : ", arr1 - arr2)
print("Mulitplication : ", arr1 * arr2)
print("Division : ", arr1 / arr2)

Addition :  [ 3  6  9 12 15]
Substraction :  [1 2 3 4 5]
Mulitplication :  [ 2  8 18 32 50]
Division :  [2. 2. 2. 2. 2.]


In [19]:
arr = np.array([2,3,4,5,6])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [25]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
print(arr[0][1])
print(arr[1:, 2:])
print(arr[0:2])
print(arr[0:2,2:])
print(arr[1:,1:3])

2
[[ 7  8]
 [11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


[[ 7  8]
 [11 12]]


In [38]:
arr[0][0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [40]:
arr[2:] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [100 100 100 100]]


In [43]:
data = np.array([1,2,3,4,5])
mean = np.mean(data)
stat_dev = np.std(data)
print(stat_dev)

normalizedData = (data - mean) / stat_dev
print(normalizedData)

median = np.median(data)
print(median)

variance = np.var(data)
print(variance)

1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
3.0
2.0


In [4]:
data = np.array([1,2,3,4,5,6,7,8,9,10]) 
print(data > 5)
print(data[data > 5])
print(data[(data > 5) & (data < 9)])
print(data[(data > 5) | (data < 9)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[6 7 8]
[ 1  2  3  4  5  6  7  8  9 10]
