In [2]:
import numpy as np
arr = np.random.randint(1, 21, size = (5, 5))
print(arr)
print()
arr[:, 2] = 1;
print(arr)
print(arr.size)

[[10 20 10 10 16]
 [15  8 20 18  6]
 [ 2 15  6 14 17]
 [17 18 19 19  9]
 [13 16 12  3  4]]

[[10 20  1 10 16]
 [15  8  1 18  6]
 [ 2 15  1 14 17]
 [17 18  1 19  9]
 [13 16  1  3  4]]
25


In [41]:
arr = np.arange(1, 17).reshape((4, 4))
arr2 = arr.copy()
for i in range(len(arr)):
    arr[i][i] = 0
    
print(arr)

arr2 = np.array(arr2)
np.fill_diagonal(arr2,0)
print(arr2)

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [55]:
arr = np.arange(1, 37).reshape((6,6))
print(arr)
subarr = arr[2:5, 1:5]
print(subarr)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]


In [56]:
arr =  np.random.randint(1, 26, size = (5, 5))
print(arr)
border = np.concatenate((arr[0, :], arr[-1, :], arr[1: -1, 0], arr[1:-1, -1]))
print(border)

[[ 1  4 12 24 10]
 [ 1 15 21  2 16]
 [23  3 14  4 15]
 [ 4 24 13 19 20]
 [15 17  5 10 18]]
[ 1  4 12 24 10 15 17  5 10 18  1 23  4 16 15 20]


In [59]:
arr = np.random.randint(1, 21, size = (3, 4))
ar2 = np.random.randint(1, 21, size = (3, 4))
print(arr)
print(ar2)
print()
add = arr + ar2
sub = arr - ar2
mult = arr * ar2
div = arr / ar2
print(add)
print(sub)
print(mult)
print(div)

[[ 4  2  1  2]
 [ 7 12  2 14]
 [ 1 20 13 14]]
[[15 18 11  3]
 [20 13 18 18]
 [20 16 18  5]]

[[19 20 12  5]
 [27 25 20 32]
 [21 36 31 19]]
[[-11 -16 -10  -1]
 [-13  -1 -16  -4]
 [-19   4  -5   9]]
[[ 60  36  11   6]
 [140 156  36 252]
 [ 20 320 234  70]]
[[0.26666667 0.11111111 0.09090909 0.66666667]
 [0.35       0.92307692 0.11111111 0.77777778]
 [0.05       1.25       0.72222222 2.8       ]]


In [5]:
arr = np.arange(1, 17).reshape((4, 4))
print(arr)
print()
row_sum = np.sum(arr, axis = 1)
col_sum = np.sum(arr, axis = 0)
print(row_sum)
print()
print(col_sum)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[10 26 42 58]

[28 32 36 40]


In [12]:
arr = np.random.randint(1, 21, size = (5, 5))
print(arr)
print()
mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)
variance = np.var(arr)
print(np.sum(arr))
print("mean",mean)
print()
print("median", median)
print()
print("std_dev", std_dev)
print()
print("variance", variance)


[[17 20 19 11  5]
 [13  8 11 17 13]
 [ 8 19 14 19  2]
 [ 5 15 14  3  2]
 [12 18 11 16 13]]

305
mean 12.2

median 13.0

std_dev 5.462600113499065

variance 29.84


In [14]:
arr = np.arange(1, 10).reshape((3, 3))
print(arr)
mean = np.mean(arr)
std_dev = np.std(arr)
normalized_arr = arr - mean / std_dev
print(normalized_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.93649167  0.06350833  1.06350833]
 [ 2.06350833  3.06350833  4.06350833]
 [ 5.06350833  6.06350833  7.06350833]]


In [16]:
arr = np.random.randint(1, 11, size=(3, 3))
row_arr = np.random.randint(1, 11, size = (3, ))
print(arr)
print(row_arr)
result = arr + row_arr
print(result)

[[ 2  1  1]
 [ 1  2  8]
 [ 1 10  4]]
[7 5 9]
[[ 9  6 10]
 [ 8  7 17]
 [ 8 15 13]]


In [23]:
arr = np.arange(1, 17).reshape(4,4)
column_arr = np.random.randint(1, 17, size=(4, ))
print("Original array:")
print(arr)
print("1D array:")
print(column_arr)
result = arr - column_arr
print("Resulting array:")
print(result)
result2 = arr - column_arr[:, np.newaxis]
print("Resulting array2 :")
print(result2)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
1D array:
[ 3 12  8 10]
Resulting array:
[[ -2 -10  -5  -6]
 [  2  -6  -1  -2]
 [  6  -2   3   2]
 [ 10   2   7   6]]
Resulting array2 :
[[-2 -1  0  1]
 [-7 -6 -5 -4]
 [ 1  2  3  4]
 [ 3  4  5  6]]


In [30]:
arr = np.random.randint(1, 11, size=(3, 3))
print(arr)


print(np.linalg.det(arr))      # determinant
print(np.linalg.inv(arr))      # inverse
print(np.linalg.eigvals(arr))  # eigenvalues

[[2 6 7]
 [8 6 2]
 [4 2 3]]
-124.00000000000003
[[-0.11290323  0.03225806  0.24193548]
 [ 0.12903226  0.17741935 -0.41935484]
 [ 0.06451613 -0.16129032  0.29032258]]
[-4.56917857 13.56917857  2.        ]


In [32]:
arr = np.random.randint(1, 11, size = (2, 3))
arr2 = np.random.randint(1, 11, size=(3, 2))
print(arr)
print(arr2)
result = np.dot(arr, arr2)
print(result)

[[8 5 6]
 [2 6 9]]
[[6 7]
 [5 5]
 [9 9]]
[[127 135]
 [123 125]]


In [34]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr)
reshaped_arr = arr.reshape(1, 9)
print(reshaped_arr)
reshaped_arr2 = arr.reshape(9, 1);
print(reshaped_arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [38]:
arr = np.random.randint(1, 26, size=(5, 5))
print(arr)
flattened_arr = arr.flatten()
print(flattened_arr)
reshaped_arr = flattened_arr.reshape(5, 5)
print(reshaped_arr)

[[ 2 19 21 16 11]
 [10 18 18 25  6]
 [21 18 24 21 21]
 [13 21 10  8 19]
 [17 13 23 11 17]]
[ 2 19 21 16 11 10 18 18 25  6 21 18 24 21 21 13 21 10  8 19 17 13 23 11
 17]
[[ 2 19 21 16 11]
 [10 18 18 25  6]
 [21 18 24 21 21]
 [13 21 10  8 19]
 [17 13 23 11 17]]


In [41]:
arr = np.random.randint(1, 26, size=(5, 5))
print(arr)
print(arr[[0, 0, -1, -1], [0, -1, 0, -1]])


[[ 5 25 14  4 16]
 [18 15  1 15 14]
 [19  9 13  1 10]
 [14 21 24  9 22]
 [ 1 11 18 20  6]]
[ 5 16  1  6]


In [43]:
arr = np.random.randint(1, 21, size=(4, 4))
print(arr)
arr[arr > 10] = 10
print(arr)

[[15  2  4 19]
 [20  6 20 18]
 [14  6  6  4]
 [ 3  7 10  5]]
[[10  2  4 10]
 [10  6 10 10]
 [10  6  6  4]
 [ 3  7 10  5]]


In [45]:
datatype = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('John', 25, 70.5), ('Alice', 30, 60.0), ('Bob', 22, 80.0)], dtype=datatype)
print(data)
sorted_data = np.sort(data, order='age')
print(sorted_data)

[('John', 25, 70.5) ('Alice', 30, 60. ) ('Bob', 22, 80. )]
[('Bob', 22, 80. ) ('John', 25, 70.5) ('Alice', 30, 60. )]


In [49]:
datatype = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=datatype)
print(data)
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [51]:
import numpy.ma as ma
arr = np.random.randint(1, 21, size = (4, 4))
masked_arr = ma.masked_greater(arr, 10)
print(arr)
print(masked_arr)
sum_masked = ma.sum(masked_arr)
print(sum_masked)

[[17 16  6 15]
 [ 8 17  1  9]
 [11  6  5 13]
 [ 2 14 12 11]]
[[-- -- 6 --]
 [8 -- 1 9]
 [-- 6 5 --]
 [2 -- -- --]]
37


In [52]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[20 13 20]
 [ 9 15 15]
 [19  7  8]]
Masked array:
[[-- 13 20]
 [9 -- 15]
 [19 7 --]]
Modified masked array:
[[13 13 20]
 [ 9 13 15]
 [19  7 13]]
